// ==========================================
// DO NOT EDIT THIS FILE MANUALLY
// This file is auto-generated by scripts/build-json-rules.mjs
// Content is compiled from src/knowledge/fragments and muiscan mappings.
// ==========================================

export const rules = `
Generate MUIBOOK component as JSON Trees.

Output JSON tree nodes with:
- type: component type
- id: unique descriptive id
- props: component props
- children: child nodes, or []

CRITICAL RULES:
1. Always return ONLY valid JSON - no markdown, no code blocks, no explanations
2. Every node MUST have: type, id, props, and children
3. IDs must be unique across the entire tree
4. Use descriptive IDs that reflect the component's purpose
5. Card content must be inside direct child CardBody.
6. Container components can have children.
7. Leaf components use children: [].
8. Props must match the component API.
9. Root additions use Container with center=true and size=medium.
10. Button and Link text stays on the component; do not wrap in Body.
11. Put visual backgrounds on layout style or SmartCard bg props.
12. SmartCard props use kebab-case: bg-image, bg-color, logo-height.
13. Normalize scanned Muibook/Figma names to Redactd component types before output.
14. Do not use Message as a styled paragraph, inline note, or form helper. Message is only for persistent page-level notices with a heading and slotted body content.
15. In Redactd JSON trees, slot placement belongs inside props, matching Muibook/MuiScan output. Example: { type: "VStack", props: { "slot": "start", ... }, children: [...] }. Do not put slot as a top-level node field.
16. Do not add CardBody.props.size just because CardBody contains SlatGroup. SlatGroup inside CardBody already triggers card-aware spacing; only use size=none when the user explicitly asks for an edge-to-edge card layout.
17. For equal Grid columns, use col="repeat(N, minmax(0, 1fr))". Do not use a numeric column count or repeat bare tracks such as "1fr 1fr 1fr"; minmax(0, 1fr) prevents content from forcing tracks wider than the Grid.
18. Layout spacing props such as space and padding must use complete CSS token references such as "var(--space-400)". Do not output "space-400", "400", or other bare scale values. Use "var(--space-000)" for zero spacing.
19. Prefer Responsive variant=container for reusable components and compositions so they react to available parent space. Use viewport responsiveness only for page-level or app-shell decisions that genuinely depend on the browser viewport.
20. Card does not have a width size scale. Card width comes from its Grid, HStack, Container, parent layout, or an explicit style when a constrained reading or form width is required. Set the size attribute on Card to propagate internal padding density to its direct CardHeader, CardBody, and CardFooter sections: medium is the default, small is compact, large is spacious, and none is edge-to-edge. Set size directly on an individual section only when Card has no size. Card-aware Tables, Accordions, and Slats remain edge-to-edge inside CardBody and inherit the per-size content inset. This inherited inset is alignment behavior, not a recommendation to derive the child component size from Card size. Choose Table, Accordion, or Slat density from the content, available width, readability, and touch-target needs. Treat Card Body size-offset stories as diagnostic references rather than canonical compositions. Medium is the safe default for complete Slat groups; avoid none or small Cards for them unless the content has been validated. Tables and Accordions can work across Card sizes when their content remains usable. A ButtonGroup inside CardFooter removes top padding while preserving size-aware inline and bottom spacing. Use usage="grid" on repeated Cards in Grid, or usage="h-stack" in an HStack with aligny="stretch", when their headers and footers should align; direct children retain document order, CardBody receives the flexible row, and composed elements such as Rule remain auto-sized. Repeated Cards should normally receive width from their parent layout rather than individual Card width styles.
21. For repeated Card clusters in a Grid, set usage="grid" on each Card. For a two-up HStack, set aligny="stretch" on HStack and usage="h-stack" on each Card. Size Card padding to column density: 1-up leaves Card size unset (default medium); 2-up leaves size unset (medium) on larger widths, adjusting down via Responsive at smaller breakpoints if needed; 3-up uses size="small"; 4-up uses size="small", or size="none" with custom padding via a space token (e.g. var(--space-300)) when edge-to-edge control is required.
22. In Drawer navigation, compose nav items as Button or Link with align="start", variant="tertiary" as the default (non-prominent) emphasis, and a slot="before" _Icon matching the item's meaning.
23. When composing Muibook charts in Redactd, populate the structured Data field through props.data, or the Series field through props.series for ComparisonChart. Redactd owns passing that value to the Muibook component. FinancialChart uses { time, open, high, low, close, volume? }. MarketSparkline and FinancialBarChart use { time, value }. ComparisonChart uses { id, label, color?, data: [{ time, value }] }. Use finite JSON numbers, unique chronological times, and coherent illustrative values. FinancialChart high/low values must contain open and close. ComparisonChart series ids must be unique; indexed and percent modes receive raw values with a non-zero first value. Follow the Structured Chart Data section for component-specific structures and examples.
24. Use slots for content projection, not as the only control for significant chrome or layout decisions in generated/editor output. When a component exposes an explicit public attr such as hide-header, use that attr instead of relying only on omitted or present slotted content. Runtime attrs such as has-header and has-footer are dynamic metadata, not authored source props.
25. Use col="1fr auto" as the default col for Slat. Do not invent a custom Slat column string from an image prompt unless the source clearly requires non-default column tracks; the default Slat columns are preferred for accessory/start/end compositions.
26. For a single side drawer opened from a menu or hamburger icon, prefer Drawer variant="push" with open and side. The side property (left or right) should match the position of the menu icon trigger. Persistent drawers are for content that stays adjacent/visible and usually do not need a menu trigger. Use workspace only for advanced editor or canvas shells with independent left/right panels around a central page. Do not use left-open, right-open, left-width, right-width, page, left, or right for overlay, push, or persistent drawers; those controls and slots are workspace-only.
27. CSS length props and style values must include valid units or CSS functions. For height, width, max-height, min-height, padding, margin, gap, and similar CSS lengths, output values such as "320px", "20rem", "100%", "100vh", "auto", or "var(--space-500)"; never output bare numeric strings such as "320" or "20" unless the component API explicitly documents a number scale for that prop.
28. Prefer Slat over an ad hoc HStack for row-like wireframe items with primary content on the left and secondary metadata, value, status, timestamp, badge, count, or action on the right. Use SlatGroup for repeated rows such as activity feeds, settings rows, account details, notifications, transaction lists, project updates, search results, or compact records. Put primary content in slot="start" and trailing metadata/action in slot="end". Always explicitly set variant="row" on standard Slat items unless creating a section header (variant="header"), interactive row (variant="action"), or custom layout; Slat items inside SlatGroup or CardBody rely on explicit variant ("row", "header", or "action") for correct automatic alignment and card/group styles.
29. For top-and-bottom positioning inside VStack (such as pushing a footer or action button to the bottom), set fill or height on VStack and apply style="align-self: end;" to the slotted child. Use fill when VStack sits inside a bounded parent (e.g. CardBody, Drawer, or Dialog); use height when specifying an explicit length (e.g. height="300px").
30. Explicitly define layout boundaries to prevent unpredictable canvas rendering. For VStack and HStack, always output width="auto" and height="auto" unless a specific dimension or fill is required.
31. For Grid, never leave col empty. It defaults to two columns (1fr 1fr), so omitting it can lead to unexpected layouts.
32. For Dialog and Drawer, omit width and height properties to inherit their design system defaults (350px and 320px respectively) unless explicitly overriding them for a specific use case.
33. When composing a user profile or avatar pattern, use AvatarChip (with image, label, and primary/secondary slotted Body) rather than constructing a custom avatar layout. If the profile pattern requires a menu or dropdown, wrap the AvatarChip inside a Button (with variant="secondary" and slot="action") inside a Dropdown, and use Menu with Buttons for the dropdown actions.
34. Badge variants are exactly neutral, positive, warning, attention, and overlay. Never output Badge variant="secondary", variant="default", or variant="error". Omit variant for the default neutral treatment. Secondary remains valid for components that explicitly document it, such as Body or Button, but not Badge.
35. Use Grid for repeated Cards, page regions, forms, and other primary layout structure. When a collection should naturally reduce its column count as its container narrows, use intrinsic tracks such as col="repeat(auto-fit, minmax(min(100%, 18rem), 1fr))" and choose the minimum width to suit the content. Use col="repeat(N, minmax(0, 1fr))" only when the requested number of columns must remain fixed.
36. Use HStack wrap only for compact inline relationships such as actions, chips, metadata, legends, and small toolbar groups that remain meaningful across multiple horizontal lines. Wrapping does not turn HStack into VStack. Do not use a wrapping HStack as the default for main page regions, card collections, forms, or a deliberate horizontal-to-vertical layout change.
37. When substantial side-by-side regions need a deliberate horizontal-to-vertical change based on available parent space, prefer a one-tree intrinsic Grid when the content can simply reflow. Use Responsive variant="container" with HStack in show-above and VStack in show-below only when the composition itself must change. Because the Responsive alternatives duplicate their child tree, do not use that swap for stateful controls, forms, duplicate ids, or content that must preserve one live instance; use a one-tree Grid or a purpose-built responsive component instead.
38. Before assigning any _Icon, inspect the available Muibook icon component names in the selected component knowledge or Custom Elements Manifest and use an exact existing mui-icon-* name. If no available icon semantically matches the requested concept, use _Icon with props.icon="mui-icon-rectangle" as the neutral Redactd fallback. Never invent an icon component or icon name.

MUI SCAN NORMALIZATION RULES:
- Normalize muiscan to Redactd types before output
- Final JSON cannot contain mui-*, raw span, TEXT, or text node types
- Core mappings:
  - mui-v-stack -> VStack
  - mui-h-stack -> HStack
  - mui-button -> Button
  - mui-link -> Link
  - mui-input -> Input
  - mui-select -> Select
  - mui-avatar-chip -> AvatarChip
  - mui-media-player -> MediaPlayer
  - mui-video-thumbnail -> VideoThumbnail
  - mui-model-viewer -> ModelViewer
  - mui-table -> Table
  - mui-row-group -> RowGroup
  - mui-row -> Row
  - mui-cell -> Cell
  - span -> Span
  - mui-icon-[name] -> _Icon with props.icon = "mui-icon-[name]"
  - mui-illustration-[name] -> _Illustration with props.illustration = "mui-illustration-[name]"
- Preserve hierarchy, spacing, slots, key props, and valid style strings
- Preserve icon slots:
  - slot=before -> props.slot = "before"
  - slot=after -> props.slot = "after"
  - if an icon is the only child of Button, Link, or Chip, keep it as the default child
- For Badge: valid output variants are neutral, positive, warning, attention, and overlay. Preserve neutral and never convert it to secondary. Omit variant for the default neutral treatment; do not output secondary, default, or error.

TEXT NODE RULES FOR MUISCAN:
- TEXT is input-only; collapse into the nearest valid Redactd text model
- Collapse TEXT -> props.text for:
  - mui-body -> Body.props.text
  - mui-heading -> Heading.props.text
  - mui-button -> Button.props.text
  - mui-link -> Link.props.text
  - mui-tab-item -> TabItem.props.text
  - mui-list-item -> ListItem.props.text
- For span:
  - convert to Span
  - consume direct TEXT into Span.props.text
  - keep inline children such as Link nested inside the same Span
- Exceptions:
  - mui-badge: consume TEXT as the badge's direct rendered text; preserve before/after slot children; do not invent Body
  - mui-status: consume TEXT as the status's direct rendered text; preserve before/after icon slot children; do not invent Body, Badge, or Message inside Status
  - mui-chip: consume TEXT as the chip's direct rendered text; preserve before/after slot children; do not invent Body
  - mui-alert: preserve variant/label, convert default content to Span, consume TEXT into Span.props.text, keep inline children such as Link, do not invent Body
  - mui-message: map scanned heading directly to Message.props.heading, preserve variant/icon/size, keep remaining children as default message content; if there is no supporting body content, prefer Body or FormMessage instead of Message
- Do not invent wrappers when the target already supports text

Available Components:

LAYOUT:
- VStack: slot, space, padding, alignX, alignY, height, width, fill, viewport, style. Use fill (100% width/height) inside bounded parents (CardBody, Drawer) or height for explicit lengths (e.g. "300px"). For bottom positioning, set fill/height on VStack and apply style="align-self: end;" to the slotted child.
- HStack: slot, space, padding, alignX, alignY, wrap, height, width, fill, viewport, style. Use wrap for compact inline relationships such as actions, chips, metadata, legends, and small toolbar groups that remain meaningful across multiple lines. Do not use wrapping HStack as the default for page regions, card collections, forms, or a deliberate horizontal-to-vertical layout change.
- Grid: slot, col, space, padding, alignX, alignY, height, width, fill, viewport, style
- Container: size (small|medium|large), center, style
- Responsive: variant (container|viewport), observe, breakpoint, breakpoint-low, breakpoint-high; slots show-below/show-middle/show-above
- Rule: length, weight (thin|thick|CSS size), direction (horizontal|vertical)

SURFACES:
- Card: size (none|small|medium|large), usage (grid|h-stack), style. Use CardBody for card content. Size propagates internal padding density to direct CardHeader, CardBody, and CardFooter sections; it does not control width. Use usage=grid on repeated Cards in Grid, or usage=h-stack in an HStack with aligny=stretch, when their headers and footers should align; direct children retain document order, CardBody receives the flexible row, and composed elements such as Rule remain auto-sized. Width is owned by Grid, HStack, Container, the parent layout, or an explicit constrained style.
- CardHeader: size (none|small|medium|large)
- CardBody: size (none|small|medium|large), style. Size controls internal padding, not Card width; medium is the default, small is compact, large is spacious, and none is edge-to-edge. Card-aware Tables, Accordions, and Slats remain edge-to-edge and inherit their content inset from Card size. At size=none, Slats retain their standard internal row inset while SlatGroup disables its negative alignment offset so rows stay within the Card border. This inset is alignment behavior, not a requirement to derive child density from Card size. Choose child size from the content, available width, readability, and touch-target needs. Treat Card Body size-offset stories as diagnostic references rather than canonical compositions. Medium is the safe default for complete Slat groups; avoid none or small Cards for them unless the content has been validated. Tables and Accordions can work across Card sizes when their content remains usable. Do not set size by default for SlatGroup layouts; leave props empty unless the user explicitly requests a spacing size.
- CardFooter: size (none|small|medium|large). A contained ButtonGroup removes top padding while preserving size-aware inline and bottom spacing.
- Dialog: open, width, content-max-height, hide-header, style. Use hide-header for unified/headerless dialogs such as confirmations, or when custom body content provides the heading and dismissal path.
- Drawer: open, variant (overlay|push|persistent|workspace), side (left|right), width, z-index, drawer-space, hide-header, breakpoint, style. For overlay, push, and persistent drawers, use open plus side to control visibility and placement; do not use left-open, right-open, left-width, right-width, page, left, or right. Use hide-header when drawer body content provides a custom header composition or custom dismissal controls. For a single side panel opened by a menu icon, prefer variant="push"; do not use workspace unless the UI is an advanced editor/canvas shell with independent side panels.
- Drawer workspace: variant=workspace, left-open, right-open, left-width, right-width, resize-rail, resize-min-drawer-width, resize-min-left-width, resize-min-right-width, resize-min-page-width, resize-close-threshold, height; slots left/page/right. Use when an editor/canvas has independent left and right panels around a central page. left-open/right-open and left/right/page slots are workspace-only. Keep direct slot wrappers plain in HTML exports when possible.
- Slat: variant (row|header|action), size (x-small|small|medium|large), col, space; child slots accessory/start/end. Medium is the default size. Action Slats pass size to their internal Button so the interactive row follows the matching action height. Always explicitly assign variant="row" for standard row slats unless creating a header (variant="header"), interactive row (variant="action"), or custom layout. When Slat is in SlatGroup or CardBody, variant ("row"|"header"|"action") is required to trigger automatic layout and alignment styles. Use col="1fr auto" by default; do not invent custom columns from an image prompt unless the source clearly requires non-default column tracks. Do not use header-start, header-end, row-start, row-end, action, or unslotted wrapper children. Put primary row content in a direct child with props.slot="start", trailing value/status/action content in a direct child with props.slot="end", and optional leading avatar/icon content in a direct child with props.slot="accessory".
- SlatGroup: usage. When SlatGroup is inside CardBody, leave CardBody size unset by default; CardBody detects SlatGroup and applies the correct card spacing automatically.
- SmartCard: state, number, variant, partner, type, logo, logo-height, bg-color, bg-image, inverted

CONTENT:
- Heading: text, size (1|2|3|4|5|6), level (1|2|3|4|5|6|none), truncate, clamp. Use level=none only for prominent values or display text that does not introduce a section; use levels 1-6 for structural headings.
- Body: text, size (xx-small|x-small|small|medium|large), weight (regular|bold), variant (default|secondary|info|positive|warning|attention), truncate, clamp, style; use _Icon icon=mui-icon-info slot=before for lightweight inline guidance
- Span: text, style; supports inline children such as Link
- Code: size, scrollable
- Quote: default text
- Image: src, alt; slot caption
- Avatar: label, image, icon, size (x-small|small|medium|large), background, backgroundColor
- AvatarChip: primary, secondary, image, label, href, target, size (x-small|small|medium|large), usage (default|media-player); slots primary/secondary. Use for compact identity metadata with an avatar and one or two text/link lines. MediaPlayer applies usage=media-player automatically when slotted into media metadata.
- List: slot default
- ListItem: text, variant, size (x-small|small|medium|large), weight (regular|bold)
- _Icon: icon, size (xx-small|x-small|small|medium|large), color, slot. Before assigning an icon, inspect the available Muibook icon names and use an exact existing mui-icon-* value. If none semantically matches the requested concept, use icon=mui-icon-rectangle as the neutral Redactd fallback. Never invent an icon component or icon name.
- _Illustration: illustration, size (x-small|small|medium|large|x-large), color, slot
- Badge: text, variant (neutral|positive|warning|attention|overlay), size (xx-small|x-small|small|medium|large), color (grey|purple|violet|pink|magenta|red|orange|amber|yellow|lime|green|teal|cyan|blue|indigo|CSS background value). Secondary, default, and error are not Badge variants. Omit variant for the default neutral treatment. Use for compact non-interactive presentational metadata, counts, and lightweight state-like labels such as Offline, Online, Busy, Do not disturb, Beta, Default, IMG, or Shared when the surrounding UI already explains the object. Good inside cards, messages, chips, buttons, tabs, navigation, and hero or marketing surfaces. Use color to override the badge background only through theme-aware badge background tokens; do not use positive, warning, or attention just to get a different background colour.
- Status: text, variant (info|positive|warning|attention), color (grey|purple|violet|pink|magenta|red|orange|amber|yellow|lime|green|teal|cyan|blue|indigo), size (x-small|small|medium); slots before/after. Use for compact object or workflow state labels such as Active, Draft, Pending, Review, Blocked, or Synced when the value is the primary state of a record, workflow, or system, especially in tables, slats, dashboards, and data-heavy pages. Use x-small next to badges or in very dense context rows. Status is non-interactive by default, but can be interactive when composed as a trigger or compact state action. Omit variant for default low-emphasis grey status; use variant for semantic feedback and color for non-semantic categorical labels. Use action only when the status is a trigger. Do not use for counts, helper text, paragraph guidance, page-level notices, or decorative metadata.
- Skeleton: loading, shape (line|rect|circle), size, animation (shimmer|pulse|none), lines, width, height, radius, gap, duration, line-widths, max-width, style
- Table: size (xx-small|x-small|small|medium|large), slot default. Use for dense desktop data layouts. Setting size on Table propagates the density to its owned heading and body Rows; medium is the default.
- RowGroup: heading; children Row.
- Row: columns, size (xx-small|x-small|small|medium|large); children Cell.
- Cell: action, align-y; children content or action controls.

ACCORDION:
- AccordionBlock: heading, level (1|2|3|4|5|6), size (xx-small|x-small|small|medium|large), detail-space. Level controls semantic document structure independently from size. Size controls heading typography, summary and detail spacing, and disclosure icon scale; medium is the default.
- AccordionInline: heading, level (1|2|3|4|5|6)
- AccordionGroup: slot default

FORMS AND INPUTS:
- FormSection: heading, hide-label, style
- FormSectionFooter: slot, style
- FormGroup: heading, variant (vertical|horizontal), hide-label, style
- Field: label, variant (default|success|warning|error), message, hide-label, size (x-small|small|medium|large), optional, style
- FormMessage: text, size (x-small|small|medium|large), weight (regular|bold), variant (secondary|info|positive|warning|attention), style
- Input: label, type (text|email|password|number|tel|url), placeholder, value, id, name, disabled, hide-label, variant (default|error), size (x-small|small|medium|large), optional, max-length; slots before/after
- Textarea: label, placeholder, value, name, id, variant (default|success|warning|error), size (x-small|small|medium|large), rows, optional, hide-label, max-length, disabled, style
- Select: label, placeholder, options, value, id, name, disabled, variant (default|error), size (x-small|small|medium|large), appearance (native|custom), selected-content (rich|label), col, space, max-height, padding-block, padding-inline. Use options for simple data selects; use Option children only when appearance=custom needs rich composed native option content.
- Option: value, label; children can contain layout/content for Select appearance=custom. Keep Option inside Select only.
- Checkbox: text, checked, id, disabled, indeterminate, size (x-small|small|medium|large)
- Radio: text, checked, disabled, id, name, value, aria-label, size (x-small|small|medium|large)
- RadioGroup: name, value, label, size (x-small|small|medium|large), optional, hide-label, disabled
- Switch: label, checked, disabled, size (x-small|small|medium|large)
- RangeInput: min, max, value, step, bubble, bubble-format (time), disabled
- ChipInput: label, placeholder, size (x-small|small|medium|large), placement (before|after), breakpoint, allow-custom, mobile-stack, hide-label, disabled, options, value, id
- FileUpload: acceptedFileTypes, currentFileName
- Addon: text, size (x-small|small|medium|large), slot (before|after), style

ACTIONS:
- Button: text, variant (primary|secondary|tertiary|overlay|attention), size (xx-small|x-small|small|medium|large), stroke (border|ring), stroke-ring-size (100|200|300|400|500), disabled, aria-label; slots default/before/after
- ButtonGroup: slot default, right, style
- Link: text, href, variant (primary|secondary|tertiary|overlay|attention), size (xx-small|x-small|small|medium|large), stroke (border|ring), stroke-ring-size (100|200|300|400|500), target, download, weight (regular|bold), disabled; slots default/before/after
- Dropdown: size (x-small|small|medium|large), zindex, position, vertical-position, persistent; slot action plus one direct Menu child. Dropdown enforces its size on the trigger and Menu. Do not place menu actions directly inside Dropdown.
- Menu: size (x-small|small|medium|large); direct Body, Button, Link, Input, Select, DatePicker, TimePicker, Textarea, SearchInput, RangeInput, and ChipInput children inherit Menu size. Menu applies size-based inset padding only to direct form-control hosts, without changing the Menu container inset. Direct Body receives action padding; Button and Link receive joined corner treatment.
- Chip: text, active, dismiss, usage; slots default/before/after. Chip labels truncate when constrained; keep text short and let icons/dismiss controls remain visible.
- ChipRail: size, aria-label; children Chip. Use for horizontally scrollable filters and category rails.

NAVIGATION:
- TabBar: speed, controlsPosition, stroke (border|none), active-inset, radius; slots default/controls
- TabItem: text, icon, active, id
- TabController: slot default
- TabPanel: item
- Stepper: direction (horizontal|vertical), activeStep
- Step: title
- CarouselController: slot default, style
- CarouselPanel: item, style

FEEDBACK:
- Message: heading, variant (neutral|positive|info|warning|attention), icon, size (small|medium|large); slot default. Use only for persistent page-level or section-level notices. Always provide a concise heading plus default slot body content, usually Body/List/Link. Do not use for inline guidance, styled text blocks, or form helper text.
- Alert: variant (success|info|warning|error), label; slots default/action
- Loader: loading, animation (pulsate|fade-in|translate), direction (up|right|down|left), duration; slot default
- Spinner: size (xx-small|x-small|small|medium|large|x-large|xx-large), color, duration, label, style
- Progress: progress, state

MEDIA:
- MediaPlayer: src, type (video|audio|youtube|soundcloud), controls (player|none), poster, artwork, media-title, height, waveform, center-play, loading, autoplay, muted, loop; slots meta-before/meta-after. Use meta-before for AvatarChip/title metadata and meta-after for overlay actions such as Subscribe or Buy now. Use variant=overlay on Button/Link actions when over video or artwork.
- VideoThumbnail: src, src-light, src-dark, src-mui-light, src-mui-dark, src-jal-light, src-jal-dark, src-ana-light, src-ana-dark, src-sensei-light, src-sensei-dark, src-paperclip-light, src-paperclip-dark, alt, play, overlay. Use inside video cards when the thumbnail needs to react to brand and light/dark theme.
- ModelViewer: src, ios-src, poster, alt, controls, camera-controls, auto-rotate, ar, loading; slots default/poster. Always include alt and fallback content when a model is important to understanding the page.

PROMPT COMPONENTS:
- Prompt: placeholder, value, rows, enter-submit, fan-open, disabled, loading, loading-label, context-mode (icon|chip), preview-dialog-width, preview-dialog-title, preview-overflow-to-preview, preview-threshold-chars, preview-auto-clickable, preview-loading, preview-loading-label, preview-scrollbar, error-message, debug, effects-off, color-top-start, color-top-mid, color-top-end, color-top-accent, color-layout, style
- ChatMessage: size (x-small|small|medium|large), variant (default|ghost), density (default|compact), style
- PreviewChip: value, badge, label, bg-image, image-tint, accent, inverted, show-text, badge-only, animated, loading, loading-label, clickable, animation-mode, style
- ActionToggle: mode (icon|chip), style

PRESENTATION:
- SlideFrame: title, footer-text, ratio (16:9|4:3|1:1|3:2|9:16), present, active-section, padding, variant (default|plain), radius, notes-open, hide-header, hide-footer, hide-counter, allow-add-section, fullscreen, scroll, style


## Structured Chart Data
When composing Muibook charts in Redactd, populate the structured **Data** field through
\`props.data\`, or the **Series** field through \`props.series\` for Comparison Chart. Redactd owns
passing that structured value to the underlying Muibook component. Do not stringify the array,
place JSON inside an HTML attribute, or generate JavaScript assignment code.

## Data contracts

- \`FinancialChart.props.data\`: \`[{ time, open, high, low, close, volume? }]\`
- \`MarketSparkline.props.data\`: \`[{ time, value }]\`
- \`FinancialBarChart.props.data\`: \`[{ time, value }]\`
- \`ComparisonChart.props.series\`: \`[{ id, label, color?, data: [{ time, value }] }]\`

For every generated dataset:

- Keep all measurements as finite JSON numbers, not formatted strings. Use \`4.2\`, \`101.28\`, or
  \`18400000\`, not \`"4.2%"\`, \`"\$101.28"\`, or \`"18.4M"\`. Formatting belongs in component props and
  composed labels.
- Use one unique \`time\` value per datum within a dataset or comparison series. Sort points from
  oldest to newest even though the components defensively sort copied input arrays.
- Prefer ISO \`YYYY-MM-DD\` strings for daily and periodic illustrative data. Unix timestamps in
  seconds or milliseconds are also accepted when supplied by the user. Do not mix time formats in
  one generated dataset.
- Match the cadence to the subject: daily points for illustrative market performance, monthly or
  quarterly points for economic and business reporting, and the user's supplied cadence when one
  exists.
- Generate enough coherent points to make the requested pattern visible. Avoid random-looking
  values, impossible OHLC relationships, duplicate dates, and placeholder sequences such as
  \`1, 2, 3\` unless that sequence is genuinely meaningful.
- Treat generated values as illustrative data. Preserve user-supplied data exactly apart from
  chronological ordering; do not silently change units, normalize values, or invent missing facts.

## Financial Chart: OHLCV market data

Use Financial Chart for open/high/low/close market observations. Candlestick and area presentations
both consume the complete OHLC shape; area charts plot each datum's \`close\`. \`volume\` is optional
and should be non-negative when supplied.

For every datum:

- \`high\` must be greater than or equal to both \`open\` and \`close\`.
- \`low\` must be less than or equal to both \`open\` and \`close\`.
- Keep all price fields in the same unit and use the matching \`currency\` label.
- Keep consecutive points plausible for the requested market and interval. The next \`open\` may
  differ from the previous \`close\`, but unexplained extreme gaps should not appear in illustrative
  data.

Example Financial Chart tree:

\`\`\`json
{
  "id": "btc_price_chart",
  "type": "FinancialChart",
  "props": {
    "symbol": "BTC/USD",
    "currency": "USD",
    "type": "candlestick",
    "interval": "1D",
    "data": [
      { "time": "2026-06-01", "open": 102400, "high": 104800, "low": 101700, "close": 103900, "volume": 18400000 },
      { "time": "2026-06-02", "open": 103900, "high": 105200, "low": 102800, "close": 104500, "volume": 16900000 },
      { "time": "2026-06-03", "open": 104500, "high": 106100, "low": 103600, "close": 105800, "volume": 21300000 }
    ]
  },
  "children": []
}
\`\`\`

## Market Sparkline: compact time/value trends

Use Market Sparkline for compact prices, indexes, yields, rates, totals, and KPI trends when shape
and direction matter more than dense inspection. Supply raw numeric values and keep currency, visible
labels, \`trend\`, \`baseline\`, and \`scale\` as component or composition props rather than embedding them
inside the data.

- A price or index trend can use ordinary positive values.
- A yield or rate uses the numeric rate value, such as \`4.38\`; a visible header can render \`4.38%\`.
- A baseline series still uses \`{ time, value }\`; set the comparison point through \`props.baseline\`.
- \`trend: "auto"\` compares the first and latest values. Do not pre-color individual data points.

Example Market Sparkline tree for a yield trend:

\`\`\`json
{
  "id": "treasury_yield_sparkline",
  "type": "MarketSparkline",
  "props": {
    "label": "US 10-year Treasury yield",
    "trend": "auto",
    "scale": "none",
    "data": [
      { "time": "2026-06-01", "value": 4.31 },
      { "time": "2026-06-02", "value": 4.35 },
      { "time": "2026-06-03", "value": 4.38 }
    ]
  },
  "children": []
}
\`\`\`

## Financial Bar Chart: periodic magnitudes and signed values

Use Financial Bar Chart for periodic economic or financial values such as inflation, interest rates,
volume, revenue, returns, and cash flow. Match formatting and color semantics to the data:

- \`value-format: "percent"\` expects ordinary percentage values such as \`4.2\`, not decimal fractions
  such as \`0.042\` and not strings such as \`"4.2%"\`.
- \`value-format: "currency"\` expects full numeric currency values and uses \`currency\` for display.
- \`value-format: "volume"\` expects full numeric quantities such as \`18400000\`; do not abbreviate the
  stored number to \`18.4\` merely because the rendered label uses compact notation.
- Use \`variant: "neutral"\` when magnitude is the main message. Use \`variant: "directional"\` when
  values above and below \`baseline\` carry positive/negative meaning. Negative values are valid.

Example monthly inflation data:

\`\`\`json
{
  "id": "inflation_bar_chart",
  "type": "FinancialBarChart",
  "props": {
    "label": "Annual inflation rate",
    "value-format": "percent",
    "variant": "neutral",
    "data": [
      { "time": "2026-01-01", "value": 3.3 },
      { "time": "2026-02-01", "value": 3.8 },
      { "time": "2026-03-01", "value": 4.2 }
    ]
  },
  "children": []
}
\`\`\`

Example signed cash-flow data:

\`\`\`json
{
  "id": "cash_flow_bar_chart",
  "type": "FinancialBarChart",
  "props": {
    "label": "Monthly net cash flow",
    "value-format": "currency",
    "currency": "USD",
    "variant": "directional",
    "baseline": 0,
    "data": [
      { "time": "2026-01-01", "value": 4200000 },
      { "time": "2026-02-01", "value": -2100000 },
      { "time": "2026-03-01", "value": 3600000 }
    ]
  },
  "children": []
}
\`\`\`

## Comparison Chart: named collections of time/value series

Comparison Chart uses \`props.series\`, never \`props.data\`. Every series needs a unique stable \`id\`, a
human-readable \`label\`, and its own chronological \`data\` array. Omit \`color\` to use the component's
theme-aware automatic series palette unless the user supplies an explicit series-color requirement.

Choose the mode before generating values:

- \`mode: "absolute"\` preserves supplied values. Use it when all series share the same unit and scale,
  such as actual versus forecast revenue. Set \`value-format\` and \`currency\` to match that unit.
- \`mode: "indexed"\` rebases each series to 100 from its own first value. Supply the original raw
  values—even when series have very different price levels—and let the component normalize them.
- \`mode: "percent"\` calculates percentage change from each series' own first value. Supply raw values,
  not precomputed percentage changes.
- Indexed and percent series need a finite, non-zero first value so the component can calculate the
  transformation.
- Series may cover different date ranges. Align dates when point-for-point comparison matters; for
  actual-versus-forecast data, sharing the handoff date can make continuity explicit.

Example indexed comparison using raw values with different magnitudes:

\`\`\`json
{
  "id": "asset_performance_comparison",
  "type": "ComparisonChart",
  "props": {
    "mode": "indexed",
    "label": "Three-asset relative performance",
    "series": [
      {
        "id": "btc",
        "label": "Bitcoin",
        "data": [
          { "time": "2026-06-01", "value": 102400 },
          { "time": "2026-06-02", "value": 104500 },
          { "time": "2026-06-03", "value": 105800 }
        ]
      },
      {
        "id": "eth",
        "label": "Ethereum",
        "data": [
          { "time": "2026-06-01", "value": 3200 },
          { "time": "2026-06-02", "value": 3180 },
          { "time": "2026-06-03", "value": 3290 }
        ]
      },
      {
        "id": "ndx",
        "label": "Nasdaq 100",
        "data": [
          { "time": "2026-06-01", "value": 19500 },
          { "time": "2026-06-02", "value": 19640 },
          { "time": "2026-06-03", "value": 19720 }
        ]
      }
    ]
  },
  "children": []
}
\`\`\`

Example actual-versus-forecast series for \`mode: "absolute"\`:

\`\`\`json
{
  "id": "revenue_forecast_comparison",
  "type": "ComparisonChart",
  "props": {
    "mode": "absolute",
    "label": "Actual and forecast revenue",
    "value-format": "currency",
    "currency": "USD",
    "series": [
      {
        "id": "actual",
        "label": "Actual revenue",
        "data": [
          { "time": "2026-01-01", "value": 8400000 },
          { "time": "2026-02-01", "value": 8900000 },
          { "time": "2026-03-01", "value": 9300000 }
        ]
      },
      {
        "id": "forecast",
        "label": "Forecast revenue",
        "data": [
          { "time": "2026-03-01", "value": 9300000 },
          { "time": "2026-04-01", "value": 9700000 },
          { "time": "2026-05-01", "value": 10100000 }
        ]
      }
    ]
  },
  "children": []
}
\`\`\`


## Composable Chart Headers
Chart headers are composable named-slot regions, not a fixed subcomponent or required anatomy.
Build them from the Muibook layout and content components that fit the information the user asks
for. The examples below are starting points to adapt, simplify, reorder, or extend; do not reproduce
every child merely because it appears in an example.

- Put the outer header layout directly inside \`MarketSparkline\`, \`FinancialBarChart\`, or
  \`ComparisonChart\` with \`props.slot: "header"\`. Slot placement stays inside \`props\`, never on the
  node itself.
- Start with the smallest useful hierarchy: a visible title and optional supporting copy. Add an
  instrument badge, current value, change, units, forecast, release date, actions, or other context
  only when it supports the requested chart.
- Use \`VStack\` for vertically grouped title, value, and supporting text. Use \`HStack\` for related
  inline metadata or to place two meaningful groups at opposite sides of a wider header. Allow
  wrapping when a split header or legend may run out of horizontal space.
- Use \`Heading\` with \`level: "none"\` for prominent values or display labels that should not create a
  document section. Use a semantic heading level when the chart title introduces a real section in
  the surrounding page hierarchy.
- Keep the chart's accessible \`label\` even when the same idea is visible in the composed header.
  Pair trends and series colors with text; color and plot shape must not carry the meaning alone.
- Market Sparkline defaults to \`scale: "none"\` so both axes stay hidden, including when it is
  interactive. Set \`scale\` to \`both\`, \`time\`, or \`price\` only when the compact trend needs a visible
  reference axis. Financial Bar Chart and Comparison Chart default to \`scale: "both"\`. Across all
  three components, the value/price scale appears on the right and the time scale along the bottom;
  \`scale\` controls which axes are visible and does not reposition them.
- \`ComparisonChart\` also exposes a \`legend\` slot. A compact legend may sit beside the title inside
  the header; use a separate child with \`props.slot: "legend"\` when the legend needs its own row or
  independent layout. Whichever placement is chosen, label every supplied series and keep legend
  colors consistent with the series.
- \`FinancialBarChart\` and \`ComparisonChart\` provide their own padded header region. Add local
  padding to a Market Sparkline header only when its surrounding Card or layout does not already
  provide the needed inset. Do not copy example padding or spacing without considering the parent.
- Use \`header-stroke\` on Financial Bar Chart or Comparison Chart only when the requested composition
  should visually join the populated header to the plot without the default divider.

Example Market Sparkline header with instrument context and a current value:

\`\`\`json
{
  "id": "dollar_index_sparkline",
  "type": "MarketSparkline",
  "props": {
    "label": "US Dollar index three month trend",
    "height": "10rem",
    "data": [
      { "time": "2026-06-01", "value": 100.72 },
      { "time": "2026-06-02", "value": 101.04 },
      { "time": "2026-06-03", "value": 101.28 }
    ]
  },
  "children": [
    {
      "id": "dollar_index_header",
      "type": "VStack",
      "props": {
        "slot": "header",
        "space": "var(--space-000)",
        "width": "auto",
        "height": "auto",
        "style": "padding: var(--space-400);"
      },
      "children": [
        {
          "id": "dollar_index_identity",
          "type": "HStack",
          "props": {
            "space": "var(--space-200)",
            "alignY": "center",
            "width": "auto",
            "height": "auto"
          },
          "children": [
            { "id": "dollar_index_name", "type": "Body", "props": { "text": "US Dollar index", "size": "small" }, "children": [] },
            { "id": "dollar_index_symbol", "type": "Badge", "props": { "text": "DXY", "size": "x-small" }, "children": [] }
          ]
        },
        {
          "id": "dollar_index_value_row",
          "type": "HStack",
          "props": {
            "space": "var(--space-200)",
            "alignY": "center",
            "width": "auto",
            "height": "auto"
          },
          "children": [
            { "id": "dollar_index_value", "type": "Heading", "props": { "text": "101.280 USD", "size": "3", "level": "none" }, "children": [] },
            { "id": "dollar_index_change", "type": "Body", "props": { "text": "+1.61%", "variant": "positive" }, "children": [] }
          ]
        }
      ]
    }
  ]
}
\`\`\`

Example Financial Bar Chart header with optional economic context:

\`\`\`json
{
  "id": "inflation_chart",
  "type": "FinancialBarChart",
  "props": {
    "label": "US annual inflation rate",
    "value-format": "percent",
    "height": "24rem",
    "data": [
      { "time": "2026-04-01", "value": 3.8 },
      { "time": "2026-05-01", "value": 4.0 },
      { "time": "2026-06-01", "value": 4.2 }
    ]
  },
  "children": [
    {
      "id": "inflation_header",
      "type": "VStack",
      "props": {
        "slot": "header",
        "space": "var(--space-400)",
        "width": "auto",
        "height": "auto"
      },
      "children": [
        {
          "id": "inflation_title_row",
          "type": "HStack",
          "props": {
            "space": "var(--space-100)",
            "alignY": "center",
            "width": "auto",
            "height": "auto"
          },
          "children": [
            { "id": "inflation_title", "type": "Heading", "props": { "text": "US annual inflation rate", "size": "4", "level": "none" }, "children": [] },
            { "id": "inflation_symbol", "type": "Badge", "props": { "text": "USIRYY", "size": "x-small" }, "children": [] }
          ]
        },
        {
          "id": "inflation_metrics",
          "type": "HStack",
          "props": {
            "space": "var(--space-600)",
            "width": "auto",
            "height": "auto",
            "wrap": true
          },
          "children": [
            {
              "id": "inflation_actual",
              "type": "VStack",
              "props": { "space": "var(--space-000)", "width": "auto", "height": "auto" },
              "children": [
                { "id": "inflation_actual_label", "type": "Body", "props": { "text": "Actual", "size": "x-small", "variant": "secondary" }, "children": [] },
                { "id": "inflation_actual_value", "type": "Heading", "props": { "text": "4.2%", "size": "4", "level": "none" }, "children": [] }
              ]
            },
            {
              "id": "inflation_forecast",
              "type": "VStack",
              "props": { "space": "var(--space-000)", "width": "auto", "height": "auto" },
              "children": [
                { "id": "inflation_forecast_label", "type": "Body", "props": { "text": "Forecast", "size": "x-small", "variant": "secondary" }, "children": [] },
                { "id": "inflation_forecast_value", "type": "Heading", "props": { "text": "4.0%", "size": "4", "level": "none" }, "children": [] }
              ]
            }
          ]
        }
      ]
    }
  ]
}
\`\`\`

Example Comparison Chart with a compact legend composed into the header:

\`\`\`json
{
  "id": "revenue_comparison",
  "type": "ComparisonChart",
  "props": {
    "mode": "absolute",
    "label": "Actual and forecast revenue",
    "value-format": "currency",
    "height": "26rem",
    "series": [
      {
        "id": "actual",
        "label": "Actual revenue",
        "data": [
          { "time": "2026-05-01", "value": 10.8 },
          { "time": "2026-06-01", "value": 11.1 }
        ]
      },
      {
        "id": "forecast",
        "label": "Forecast revenue",
        "data": [
          { "time": "2026-06-01", "value": 11.1 },
          { "time": "2026-07-01", "value": 11.6 }
        ]
      }
    ]
  },
  "children": [
    {
      "id": "revenue_comparison_header",
      "type": "HStack",
      "props": {
        "slot": "header",
        "alignX": "space-between",
        "alignY": "center",
        "space": "var(--space-400)",
        "width": "auto",
        "height": "auto",
        "wrap": true
      },
      "children": [
        {
          "id": "revenue_comparison_title_group",
          "type": "VStack",
          "props": { "space": "var(--space-100)", "width": "auto", "height": "auto" },
          "children": [
            { "id": "revenue_comparison_title", "type": "Heading", "props": { "text": "Actual and forecast revenue", "size": "4", "level": "none" }, "children": [] },
            { "id": "revenue_comparison_unit", "type": "Body", "props": { "text": "USD billions", "size": "small", "variant": "secondary" }, "children": [] }
          ]
        },
        {
          "id": "revenue_comparison_legend",
          "type": "HStack",
          "props": { "space": "var(--space-300)", "width": "auto", "height": "auto", "wrap": true },
          "children": [
            { "id": "actual_legend_badge", "type": "Badge", "props": { "text": "Actual", "size": "x-small", "color": "blue" }, "children": [] },
            { "id": "forecast_legend_badge", "type": "Badge", "props": { "text": "Forecast", "size": "x-small", "color": "green" }, "children": [] }
          ]
        }
      ]
    }
  ]
}
\`\`\`


## Spacing Values

000, 025, 050, 100, 200, 300, 400, 500, 600, 700, 800
Use 100-300 for tight/form spacing and 400-800 for layout.

## Assets

Use real Muibook asset paths:
- Base path: 'https://muibook.com/images/'
- Logos: 'logo.png', 'guides.svg', 'mui.svg'
- Backgrounds: 'placeholder.png', 'snowy-mint.png', 'buttercup.png', 'sapphire.png', 'crystal.png', 'premier.png', 'diamond.png'
- Partners: 'mastercard.svg', 'visa-black.svg', 'visa-white.svg', 'amex.svg', 'emerald.svg', 'ruby.svg', 'sapphire.svg'

## Formatting

- SmartCard number: last four digits only (e.g. 1234).

`;
