export const keywords: Record<string, string[]> = {
  // FEEDBACK
  alert: ["alert", "success", "info", "warning", "error", "message", "banner", "notification"],
  message: [
    "page message",
    "page notice",
    "persistent notice",
    "persistent message",
    "system notice",
    "status notice",
    "message banner",
  ],
  loader: ["loader", "loading", "skeleton", "placeholder", "shimmer", "pulse", "fade", "spinner"],
  spinner: ["spinner", "loading", "busy", "indicator", "progress"],
  progress: ["progress", "bar", "loading", "completion", "percent", "syncing", "pending"],

  // ACTIONS
  button: ["button", "click", "action", "submit", "cta", "primary", "secondary", "tertiary", "attention"],
  "button-group": ["button group", "buttons", "actions", "group", "right", "align"],
  link: ["link", "anchor", "hyperlink", "navigation", "primary", "secondary", "tertiary", "attention"],
  dropdown: ["dropdown", "menu", "popover", "context menu", "action menu"],
  chip: ["chip", "tag", "filter", "active", "dismiss", "input chip"],
  chipRail: ["chip rail", "filter rail", "scrolling chips", "chip navigation", "horizontal filters"],

  // CONTENT
  icon: [
    "icon",
    "glyph",
    "symbol",
    "add",
    "plus",
    "close",
    "x",
    "check",
    "tick",
    "warning",
    "alert",
    "chevron",
    "arrow",
    "accessibility",
    "sun",
    "moon",
    "info",
    "stop",
    "globe",
    "menu",
    "ellipsis",
    "grid",
    "message",
    "sidebar",
    "subtract",
    "minus",
  ],
  heading: ["heading", "title", "h1", "h2", "h3", "size", "level"],
  body: ["body", "text", "paragraph", "copy", "default", "secondary", "info", "positive", "warning", "attention"],
  span: ["span", "inline", "text", "rich text", "inline link"],
  code: ["code", "snippet", "monospace", "pre", "syntax"],
  quote: ["quote", "blockquote", "citation", "pull quote"],
  list: ["list", "items", "ul", "li", "ordered", "unordered"],
  avatar: ["avatar", "profile", "user", "initials", "image", "icon", "person"],
  image: ["image", "photo", "picture", "figure", "caption", "img"],
  illustrations: ["illustration", "empty state", "graphic", "artwork", "visual"],
  markdown: ["markdown", "md", "rich content", "formatted content", "prose"],
  skeleton: ["skeleton", "loading", "placeholder", "shimmer", "pulse", "line", "rect", "circle"],
  badge: [
    "badge",
    "count",
    "label",
    "tag",
    "metadata",
    "notification",
    "overlay",
    "paid",
    "busy",
    "offline",
    "beta",
    "default",
    "shared",
    "positive",
    "warning",
    "error",
  ],
  status: [
    "status",
    "state",
    "workflow state",
    "record status",
    "object status",
    "active",
    "draft",
    "pending",
    "review",
    "blocked",
    "synced",
    "queued",
  ],

  // ACCORDION
  accordion: [
    "accordion",
    "collapse",
    "expand",
    "toggle",
    "show more",
    "disclosure",
    "section",
    "detail",
    "summary",
    "accordion block",
    "accordion inline",
    "accordion group",
  ],

  // LAYOUT
  stack: ["stack", "v-stack", "h-stack", "vertical", "horizontal", "spacing"],
  grid: ["grid", "columns", "rows", "layout", "container"],
  container: ["container", "wrapper", "layout", "section"],
  responsive: ["responsive", "breakpoint", "mobile", "desktop", "show-above", "show-below"],
  rule: ["rule", "divider", "separator", "line", "hr"],

  // SURFACES
  card: ["card", "panel", "box", "tile"],
  dialog: ["dialog", "modal", "popup", "overlay", "lightbox", "confirm"],
  drawer: ["drawer", "sidebar", "panel", "slide", "overlay", "push", "persistent", "left", "right"],
  slat: [
    "slat",
    "row",
    "summary",
    "item row",
    "preview",
    "cell",
    "list item",
    "entry",
    "stacked",
    "slat header",
    "slat action",
    "slat content",
  ],
  table: [
    "table",
    "data table",
    "grid",
    "data grid",
    "spreadsheet",
    "rows",
    "columns",
    "cells",
    "header row",
    "data",
    "record",
    "tabular",
  ],
  mediaPlayer: [
    "media player",
    "video",
    "audio",
    "player",
    "playback",
    "controls",
    "poster",
    "artwork",
    "waveform",
    "picture in picture",
    "fullscreen",
  ],
  videoThumbnail: ["video thumbnail", "thumbnail", "video preview", "poster", "play overlay", "preview card"],
  smartCard: [
    "card",
    "smart card",
    "debit",
    "credit",
    "reward",
    "payment",
    "bank",
    "plain",
    "animated",
    "inverted",
    "frozen",
    "logo",
    "partner",
    "network",
    "diamond",
    "premier",
    "sapphire",
    "crystal",
    "visa",
    "mastercard",
    "amex",
    "payment network",
    "background image",
    "bg-image",
    "background color",
    "bg-color",
    "number",
    "type",
    "variant",
    "state",
  ],

  // FORMS AND INPUTS
  input: ["input", "text field", "text input", "field", "entry", "form field"],
  searchInput: [
    "search input",
    "search",
    "filter",
    "search field",
    "search box",
    "toolbar search",
    "reveal search",
    "search tabs",
  ],
  textarea: ["textarea", "text area", "multiline", "long text", "message", "description", "rows"],
  select: ["select", "dropdown", "picker", "options", "choose", "combobox"],
  checkbox: ["checkbox", "check", "tick", "agree", "terms", "boolean", "toggle"],
  radio: ["radio", "radio button", "option", "choose one", "single select"],
  radioGroup: ["radio group", "radio options", "single choice group", "option group"],
  switch: ["switch", "toggle", "on off", "enable", "disable", "boolean"],
  field: ["field", "form field", "label", "input wrapper", "validation", "error", "success", "warning"],
  "form-group": ["form group", "form", "group", "vertical", "horizontal", "fieldset"],
  "form-section": ["form section", "section", "form heading", "grouped fields"],
  formSectionFooter: ["form section footer", "form footer", "form actions", "section actions"],
  "form-message": ["form message", "hint", "helper text", "validation message", "field message"],
  formHint: ["form hint", "hint", "helper text", "field help", "supporting text"],
  hint: ["hint", "tooltip", "help text", "assistive hint", "supporting context"],
  rangeInput: ["range", "slider", "min", "max", "step", "range input", "scrubber"],
  chipInput: ["chip input", "tag input", "multi select", "token input", "chips"],
  fileUpload: ["file upload", "upload", "attach", "file", "drag and drop", "attachment"],
  addOn: ["addon", "input after", "input before", "prefix", "suffix", "unit", "currency"],

  // NAVIGATION
  tab: ["tab", "tab bar", "tab controller", "tab panel", "navigation", "tabs"],
  carousel: ["carousel", "slider", "carousel controller", "carousel panel", "carousel item", "carousel tabs"],
  stepper: ["stepper", "steps", "wizard", "progress steps", "multi step", "step indicator"],

  // PROMPT
  prompt: ["prompt", "ai prompt", "chat input", "message input", "fan", "context", "preview", "submit"],
  agentPrompt: ["agent prompt", "assistant prompt", "system prompt", "llm prompt", "agent input"],
  agentBubble: ["agent bubble", "assistant bubble", "chat bubble", "ai response", "agent message"],
  chatMessage: ["chat message", "prompt message", "ai message", "ghost", "compact", "density"],
  previewChip: ["preview chip", "prompt preview", "preview", "badge", "image preview", "animated preview"],
  actionToggle: ["action toggle", "prompt toggle", "toggle", "icon mode", "chip mode"],

  // PRESENTATION
  slideFrame: ["slide", "slides", "presentation", "slide frame", "deck", "ratio", "fullscreen", "section", "notes"],
  slideSection: ["slide section", "deck section", "presentation section", "chapter", "section divider"],
};

export const agentKeywordKeys = [
  "alert",
  "message",
  "loader",
  "spinner",
  "progress",
  "button",
  "button-group",
  "link",
  "dropdown",
  "chip",
  "icon",
  "heading",
  "body",
  "span",
  "code",
  "quote",
  "list",
  "avatar",
  "image",
  "skeleton",
  "badge",
  "status",
  "accordion",
  "stack",
  "grid",
  "container",
  "responsive",
  "rule",
  "card",
  "dialog",
  "drawer",
  "slat",
  "table",
  "smartCard",
  "input",
  "searchInput",
  "textarea",
  "select",
  "checkbox",
  "radio",
  "switch",
  "field",
  "form-group",
  "form-section",
  "form-message",
  "rangeInput",
  "chipInput",
  "fileUpload",
  "addOn",
  "tab",
  "carousel",
  "stepper",
  "prompt",
  "chatMessage",
  "previewChip",
  "actionToggle",
  "slideFrame",
] as const;

export type AgentKeywordKey = (typeof agentKeywordKeys)[number];

export const agentKeywords = agentKeywordKeys.reduce(
  (items, key) => ({
    ...items,
    [key]: keywords[key],
  }),
  {} as Pick<typeof keywords, AgentKeywordKey>,
);
